### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [jikan-me/website#68]
Hey there!

I belong to an open source security research community, and a member (@sinkaroid) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by irfan-dahir** [comment]
Hi @JamieSlome , I'll add the security file soon.

Meanwhile you can share the issue here publicly. Thanks

**Comment by JamieSlome** [comment]
@irfan-dahir - thanks for your response 👍 

The report can be found directly here:
https://huntr.dev/bounties/eb46a91b-3573-40e8-98e0-c1c328bfd35f/

Let me know if you have any questions.

**Comment by irfan-dahir** [comment]
@JamieSlome Could you please make it public or share it here? I do not wish to sign up to view it.

**Comment by JamieSlome** [comment]
@irfan-dahir - the report is now public:

https://huntr.dev/bounties/eb46a91b-3573-40e8-98e0-c1c328bfd35f/

**Comment by irfan-dahir** [comment]
@JamieSlome @sinkaroid Thank you for submitting a security issue. After a thorough review of the exploit mentioned, I've deemed it a non-issue.

The website is purely a client-side static site without any requests being sent via POST or allowing for an XSS attack that can be shared with others. The input form in question is simply a demo of the [APIs search call](https://github.com/jikan-me/jikan-rest) and all inputs which are sent to the said call are sanitized on an [API level](https://api.jikan.moe/v4/anime?q=bleach).

The mentioned exploit is a **self-XSS**, which does not record the query in the URL and neither does any sort provided via XSS exploit is returned by the API call or in the response. There's no way to auto-trigger it or force any POST request because there are only read-only GET requests being made to the server. Additionally, the static site is not of the same origin as the API server (where the search request is being made).

Thus, there is no attack vector present in this project.

Thank you for your insight on Github's recommendation for a `security.md` policy, that is something I will look into in the near future.

**Comment by JamieSlome** [comment]
Thanks, @irfan-dahir! 👍 

I have gone ahead and marked the report as not applicable...

**Comment by sinkaroid** [comment]
Understandable. Thanks for this neat feedback @irfan-dahir @JamieSlome
